server:
  port: 8083
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://118.190.65.33:3306/jingtongcloud
      username: root
      password: Jby&*2016
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://118.190.65.33:3306/jingtongcloud
      username: root
      password: Jby&*2016
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://118.190.65.33:3306/jingtongcloud
      username: root
      password: Jby&*2016
      driver-class-name: com.mysql.cj.jdbc.Driver
